In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [5]:
data=pd.read_csv("D:\RAJ\AI\datasets_13214_17927_Churn_Modelling.csv")

In [6]:
data.shape

(10000, 14)

In [9]:
data.head


<bound method NDFrame.head of       RowNumber  CustomerId    Surname  CreditScore Geography  Gender  Age  \
0             1    15634602   Hargrave          619    France  Female   42   
1             2    15647311       Hill          608     Spain  Female   41   
2             3    15619304       Onio          502    France  Female   42   
3             4    15701354       Boni          699    France  Female   39   
4             5    15737888   Mitchell          850     Spain  Female   43   
...         ...         ...        ...          ...       ...     ...  ...   
9995       9996    15606229   Obijiaku          771    France    Male   39   
9996       9997    15569892  Johnstone          516    France    Male   35   
9997       9998    15584532        Liu          709    France  Female   36   
9998       9999    15682355  Sabbatini          772   Germany    Male   42   
9999      10000    15628319     Walker          792    France  Female   28   

      Tenure    Balance  NumOfPro

In [12]:
x=data.iloc[:,3:13]
y=data.iloc[:,13]

In [13]:
x.shape

(10000, 10)

In [14]:
y.shape

(10000,)

In [25]:
geography=pd.get_dummies(x["Geography"],drop_first=True)
gender=pd.get_dummies(x['Gender'],drop_first=True)
geography

Germany  Spain
0           0      0
1           0      1
2           0      0
3           0      0
4           0      1
...       ...    ...
9995        0      0
9996        0      0
9997        0      0
9998        1      0
9999        0      0

[10000 rows x 2 columns]

In [20]:
x.shape

(10000, 10)

In [21]:
x.head

<bound method NDFrame.head of       CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0             619    France  Female   42       2       0.00              1   
1             608     Spain  Female   41       1   83807.86              1   
2             502    France  Female   42       8  159660.80              3   
3             699    France  Female   39       1       0.00              2   
4             850     Spain  Female   43       2  125510.82              1   
...           ...       ...     ...  ...     ...        ...            ...   
9995          771    France    Male   39       5       0.00              2   
9996          516    France    Male   35      10   57369.61              1   
9997          709    France  Female   36       7       0.00              1   
9998          772   Germany    Male   42       3   75075.31              2   
9999          792    France  Female   28       4  130142.79              1   

      HasCrCard  IsActiveMember  

In [27]:
x=pd.concat([x,geography,gender],axis=1)

In [31]:
x=x.drop(['Geography','Gender'], axis=1)

In [32]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 0)

In [33]:
x_train.shape

(8000, 11)

In [34]:
y_train.shape

(8000,)

In [35]:
from sklearn.preprocessing import StandardScaler

In [36]:
sc=StandardScaler()


In [37]:
x_train=sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [38]:
x_train.shape

(8000, 11)

In [40]:
x_train

array([[ 0.16958176, -0.46460796,  0.00666099, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-2.30455945,  0.30102557, -1.37744033, ...,  1.75486502,
        -0.57369368,  0.91601335],
       [-1.19119591, -0.94312892, -1.031415  , ..., -0.5698444 ,
        -0.57369368, -1.09168714],
       ...,
       [ 0.9015152 , -0.36890377,  0.00666099, ..., -0.5698444 ,
        -0.57369368,  0.91601335],
       [-0.62420521, -0.08179119,  1.39076231, ..., -0.5698444 ,
         1.74309049, -1.09168714],
       [-0.28401079,  0.87525072, -1.37744033, ...,  1.75486502,
        -0.57369368, -1.09168714]])

In [41]:
import keras
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LeakyReLU,PReLU,ELU
from keras.layers import Dropout

Using TensorFlow backend.
D:\UserGuidePDF\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:523: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
D:\UserGuidePDF\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:524: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
D:\UserGuidePDF\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
D:\UserGuidePDF\Anaconda\lib\site-packages\tensorflow\python\framework\dtypes.py

In [42]:
Classifier=Sequential()

In [44]:
Classifier.add(Dense(5,init = 'he_uniform', activation='relu',input_dim=11))
Classifier.add(Dense(output_dim = 6, init = 'he_uniform',activation='relu'))
Classifier.add(Dense(1, init = 'glorot_uniform', activation = 'sigmoid'))
Classifier.compile(loss='binary_crossentropy',optimizer='adam',metrics=['accuracy'])
model_history= Classifier.fit(x_train,y_train,validation_split=0.33, batch_size = 10, epochs=100)


D:\UserGuidePDF\Anaconda\lib\site-packages\ipykernel_launcher.py:1: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(5, activation="relu", input_dim=11, kernel_initializer="he_uniform")`
  """Entry point for launching an IPython kernel.
D:\UserGuidePDF\Anaconda\lib\site-packages\ipykernel_launcher.py:2: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(activation="relu", units=6, kernel_initializer="he_uniform")`
  
D:\UserGuidePDF\Anaconda\lib\site-packages\ipykernel_launcher.py:3: UserWarning: Update your `Dense` call to the Keras 2 API: `Dense(1, activation="sigmoid", kernel_initializer="glorot_uniform")`
  This is separate from the ipykernel package so we can avoid doing imports until


Train on 5359 samples, validate on 2641 samples
Epoch 1/100
5359/5359 [==============================] - 1s 249us/step - loss: 0.5539 - accuracy: 0.7770 - val_loss: 0.5044 - val_accuracy: 0.7955
Epoch 2/100
5359/5359 [==============================] - 1s 111us/step - loss: 0.4941 - accuracy: 0.7962 - val_loss: 0.4788 - val_accuracy: 0.7955
Epoch 3/100
5359/5359 [==============================] - 1s 105us/step - loss: 0.4585 - accuracy: 0.7962 - val_loss: 0.4437 - val_accuracy: 0.7955
Epoch 4/100
5359/5359 [==============================] - 1s 107us/step - loss: 0.4200 - accuracy: 0.7962 - val_loss: 0.4160 - val_accuracy: 0.7955
Epoch 5/100
5359/5359 [==============================] - ETA: 0s - loss: 0.3968 - accuracy: 0.81 - 1s 110us/step - loss: 0.3953 - accuracy: 0.8177 - val_loss: 0.3999 - val_accuracy: 0.8281
Epoch 6/100
5359/5359 [==============================] - 1s 116us/step - loss: 0.3819 - accuracy: 0.8416 - val_loss: 0.3939 - val_accuracy: 0.8247
Epoch 7/100
5359/5359 [=====

In [49]:
y_pred = Classifier.predict(x_test)
y_pred = (y_pred > 0.5)


In [50]:
y_pred 

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [54]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1501,   94],
       [ 198,  207]], dtype=int64)

In [52]:
from sklearn.metrics import accuracy_score
score=accuracy_score(y_pred,y_test)

In [53]:
score

0.854