In [70]:
import numpy 
import matplotlib.pyplot as plt
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import pandas 
import math
from tensorflow.keras.layers import LSTM
from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_squared_error


In [11]:
dataset=pandas.read_csv(r"D:\RAJ\AI\dataset\airline-passengers1.csv")

In [14]:
dataset.head

<bound method NDFrame.head of        Month  Passengers
0    1949-01         112
1    1949-02         118
2    1949-03         132
3    1949-04         129
4    1949-05         121
..       ...         ...
139  1960-08         606
140  1960-09         508
141  1960-10         461
142  1960-11         390
143  1960-12         432

[144 rows x 2 columns]>

In [21]:
data=dataset.iloc[:,1]

In [22]:
data.head

<bound method NDFrame.head of 0      112
1      118
2      132
3      129
4      121
      ... 
139    606
140    508
141    461
142    390
143    432
Name: Passengers, Length: 144, dtype: int64>

In [62]:
dataset=data.astype('float32')
dataset=data.values
type(dataset)
dataset.shape

(144,)

In [63]:
dataset=dataset.reshape(144,1)


In [64]:
dataset.shape

(144, 1)

In [65]:
scaler = MinMaxScaler(feature_range=(0, 1))
dataset = scaler.fit_transform(dataset)
dataset.shape
dataset



array([[0.01544402],
       [0.02702703],
       [0.05405405],
       [0.04826255],
       [0.03281853],
       [0.05984556],
       [0.08494208],
       [0.08494208],
       [0.06177606],
       [0.02895753],
       [0.        ],
       [0.02702703],
       [0.02123552],
       [0.04247104],
       [0.07142857],
       [0.05984556],
       [0.04054054],
       [0.08687259],
       [0.12741313],
       [0.12741313],
       [0.1042471 ],
       [0.05598456],
       [0.01930502],
       [0.06949807],
       [0.07915058],
       [0.08880309],
       [0.14285714],
       [0.11389961],
       [0.13127413],
       [0.14285714],
       [0.18339768],
       [0.18339768],
       [0.15444015],
       [0.11196911],
       [0.08108108],
       [0.11969112],
       [0.12934363],
       [0.14671815],
       [0.17181467],
       [0.14864865],
       [0.15250965],
       [0.22007722],
       [0.24324324],
       [0.26640927],
       [0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.173

In [66]:
train_size = int(len(dataset)*0.7)
test_size=len(dataset)-train_size
train = dataset[test_size:len(dataset),:]
test = dataset[0:test_size,:]
print(len(train), len(test))
print(train.shape)
print(test.shape)
train



100 44
(100, 1)
(44, 1)


array([[0.2027027 ],
       [0.16795367],
       [0.13127413],
       [0.17374517],
       [0.17760618],
       [0.17760618],
       [0.25482625],
       [0.25289575],
       [0.24131274],
       [0.26833977],
       [0.30888031],
       [0.32432432],
       [0.25675676],
       [0.20656371],
       [0.14671815],
       [0.18725869],
       [0.19305019],
       [0.16216216],
       [0.25289575],
       [0.23745174],
       [0.25096525],
       [0.30888031],
       [0.38223938],
       [0.36486486],
       [0.2992278 ],
       [0.24131274],
       [0.19111969],
       [0.24131274],
       [0.26640927],
       [0.24903475],
       [0.31467181],
       [0.31853282],
       [0.32046332],
       [0.40733591],
       [0.5019305 ],
       [0.46911197],
       [0.4015444 ],
       [0.32818533],
       [0.25675676],
       [0.33590734],
       [0.34749035],
       [0.33397683],
       [0.41119691],
       [0.4034749 ],
       [0.41312741],
       [0.52123552],
       [0.5965251 ],
       [0.581

In [71]:
def create_dataset(data, look_back):
    dataX, dataY = [], []

    for i in range(len(data)-look_back-1):
        a = data[i:(i+look_back), 0]
        dataX.append(a)
        dataY.append(data[i + look_back, 0])  
    return numpy.array(dataX), numpy.array(dataY)



In [72]:
look_back = 1
trainX, trainY = create_dataset(train, look_back)
testX, testY = create_dataset(test, look_back)
print(trainX.shape)
print(trainY.shape)
print(testX.shape)
print(testY.shape)

(98, 1)
(98,)
(42, 1)
(42,)


In [73]:
trainX = numpy.reshape(trainX, (trainX.shape[0], 1, trainX.shape[1]))
testX = numpy.reshape(testX, (testX.shape[0], 1, testX.shape[1]))
print(trainX.shape)
print(trainY.shape)
print(testX.shape)
print(testY.shape)

(98, 1, 1)
(98,)
(42, 1, 1)
(42,)


In [74]:
model = Sequential()
model.add(LSTM(4, input_shape=(1,1)))
model.add(Dense(1))
model.compile(loss='mean_squared_error', optimizer='adam', metrics=['accuracy'])
model.fit(trainX, trainY, epochs=1000)

Epoch 1/1000
98/98 [==============================] - 1s 8ms/sample - loss: 0.2334 - accuracy: 0.0000e+00
Epoch 2/1000
98/98 [==============================] - 0s 102us/sample - loss: 0.2271 - accuracy: 0.0000e+00
Epoch 3/1000
98/98 [==============================] - 0s 82us/sample - loss: 0.2211 - accuracy: 0.0000e+00
Epoch 4/1000
98/98 [==============================] - 0s 61us/sample - loss: 0.2151 - accuracy: 0.0000e+00
Epoch 5/1000
98/98 [==============================] - 0s 71us/sample - loss: 0.2093 - accuracy: 0.0000e+00
Epoch 6/1000
98/98 [==============================] - 0s 72us/sample - loss: 0.2036 - accuracy: 0.0000e+00
Epoch 7/1000
98/98 [==============================] - 0s 81us/sample - loss: 0.1980 - accuracy: 0.0000e+00
Epoch 8/1000
98/98 [==============================] - 0s 82us/sample - loss: 0.1925 - accuracy: 0.0000e+00
Epoch 9/1000
98/98 [==============================] - 0s 71us/sample - loss: 0.1872 - accuracy: 0.0000e+00
Epoch 10/1000
98/98 [================

In [75]:
trainPredict = model.predict(trainX)
#print(trainPredict)
testPredict = model.predict(testX)
#print([trainY])
# invert predictions
trainPredict = scaler.inverse_transform(trainPredict)
print(trainY.shape)
trainY = scaler.inverse_transform([trainY])
testPredict = scaler.inverse_transform(testPredict)
testY = scaler.inverse_transform([testY])
# calculate root mean squared error
trainScore = math.sqrt(mean_squared_error(trainY[0], trainPredict[:,0]))
print('Train Score: %.2f RMSE' % (trainScore))
testScore = math.sqrt(mean_squared_error(testY[0], testPredict[:,0]))
print('Test Score: %.2f RMSE' % (testScore))

(98,)
Train Score: 38.13 RMSE
Test Score: 22.79 RMSE


In [76]:

trainPredict.shape

(98, 1)

In [77]:


testPredict

array([[140.87134],
       [145.26048],
       [155.73514],
       [153.46342],
       [147.47774],
       [158.02144],
       [168.0943 ],
       [168.0943 ],
       [158.78676],
       [145.9979 ],
       [135.1143 ],
       [145.26048],
       [143.05832],
       [151.2064 ],
       [162.63733],
       [158.02144],
       [150.45738],
       [168.8801 ],
       [185.7285 ],
       [185.7285 ],
       [176.02077],
       [156.4956 ],
       [142.32764],
       [161.86403],
       [165.74623],
       [169.66742],
       [192.3142 ],
       [180.0402 ],
       [187.36656],
       [192.3142 ],
       [210.00671],
       [210.00671],
       [197.31079],
       [179.23338],
       [166.52737],
       [182.4694 ],
       [186.54681],
       [193.97435],
       [204.8943 ],
       [194.80646],
       [196.4747 ],
       [226.47409]], dtype=float32)

In [78]:
testY

array([[118., 132., 129., 121., 135., 148., 148., 136., 119., 104., 118.,
        115., 126., 141., 135., 125., 149., 170., 170., 158., 133., 114.,
        140., 145., 150., 178., 163., 172., 178., 199., 199., 184., 162.,
        146., 166., 171., 180., 193., 181., 183., 218., 230.]])